### ISSUE TITLE
RuntimeError: Detected that custom integration 'camect' calls async_fire

### ISSUE THREAD

**Issue by pfunkmallone** [Fr3d/camect-ha#4]
Getting the following error in my logs. HomeAssistant version 2024.05.02 and camect-ha version 1.0.1:

```
2024-05-06 14:39:41.123 INFO (Thread-2 (run_until_complete)) [custom_components.camect.camecthub] Firing camera event to bus: {'device_id': 'camera.camect_<camnumber>', 'type': 'alert', 'raw_data': {'type': 'alert', 'desc': 'Deck just saw a person.', 'url': 'https://home.camect.com/v2/#hid=<hidnumber>&cid=<cidnumber>&ts=1715024375549', 'cam_id': '<camid>', 'cam_name': 'Deck', 'detected_obj': ['person'], 'roi': {'contour': [{'point': [{'x': 0.55, 'y': 0.22222222}, {'x': 0.325, 'y': 0.26666668}, {'x': 0.325, 'y': 0.4}, {'x': 0.4, 'y': 0.46666667}, {'x': 0.5375, 'y': 0.46666667}]}], 'object': [{'name': 'person', 'min_size': 0.0021896076, 'max_size': 0.019480035, 'contour': [{'point': [{'x': 0.55, 'y': 0.22222222}, {'x': 0.325, 'y': 0.26666668}, {'x': 0.325, 'y': 0.4}, {'x': 0.4125, 'y': 0.46666667}, {'x': 0.5375, 'y': 0.46666667}]}], 'movement_trace': {'point': [{'x': 0.36269304, 'y': 0.36647344}, {'x': 0.3623377, 'y': 0.35872298}, {'x': 0.36585224, 'y': 0.37099564}, {'x': 0.36805278, 'y': 0.35538453}, {'x': 0.37259597, 'y': 0.34865388}, {'x': 0.38186523, 'y': 0.34194857}, {'x': 0.38925326, 'y': 0.37794116}, {'x': 0.4077111, 'y': 0.35638523}, {'x': 0.4052499, 'y': 0.3838465}, {'x': 0.41196895, 'y': 0.35945958}, {'x': 0.42054307, 'y': 0.3647266}, {'x': 0.43033668, 'y': 0.36274052}, {'x': 0.44650888, 'y': 0.36441424}, {'x': 0.45191425, 'y': 0.3680178}, {'x': 0.48173195, 'y': 0.36561066}, {'x': 0.48786986, 'y': 0.36666667}, {'x': 0.4935326, 'y': 0.36803946}, {'x': 0.50142086, 'y': 0.36537328}, {'x': 0.5087515, 'y': 0.3639211}, {'x': 0.5122759, 'y': 0.35339713}]}}]}}}
2024-05-06 14:39:41.129 WARNING (Thread-2 (run_until_complete)) [homeassistant.helpers.frame] Detected that custom integration 'camect' calls async_fire from a thread at custom_components/camect/camecthub.py, line 223: self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data), please report it to the author of the 'camect' custom integration
2024-05-06 14:39:41.130 ERROR (Thread-2 (run_until_complete)) [custom_components.camect.camecthub] Unknown error receiving event: {'type': 'alert', 'desc': 'Deck just saw a person.', 'url': 'https://home.camect.com/v2/#hid=<hidnumber>&cid=<cidnumber>4&ts=1715024375549', 'cam_id': '<camid>', 'cam_name': 'Deck', 'detected_obj': ['person'], 'roi': {'contour': [{'point': [{'x': 0.55, 'y': 0.22222222}, {'x': 0.325, 'y': 0.26666668}, {'x': 0.325, 'y': 0.4}, {'x': 0.4, 'y': 0.46666667}, {'x': 0.5375, 'y': 0.46666667}]}], 'object': [{'name': 'person', 'min_size': 0.0021896076, 'max_size': 0.019480035, 'contour': [{'point': [{'x': 0.55, 'y': 0.22222222}, {'x': 0.325, 'y': 0.26666668}, {'x': 0.325, 'y': 0.4}, {'x': 0.4125, 'y': 0.46666667}, {'x': 0.5375, 'y': 0.46666667}]}], 'movement_trace': {'point': [{'x': 0.36269304, 'y': 0.36647344}, {'x': 0.3623377, 'y': 0.35872298}, {'x': 0.36585224, 'y': 0.37099564}, {'x': 0.36805278, 'y': 0.35538453}, {'x': 0.37259597, 'y': 0.34865388}, {'x': 0.38186523, 'y': 0.34194857}, {'x': 0.38925326, 'y': 0.37794116}, {'x': 0.4077111, 'y': 0.35638523}, {'x': 0.4052499, 'y': 0.3838465}, {'x': 0.41196895, 'y': 0.35945958}, {'x': 0.42054307, 'y': 0.3647266}, {'x': 0.43033668, 'y': 0.36274052}, {'x': 0.44650888, 'y': 0.36441424}, {'x': 0.45191425, 'y': 0.3680178}, {'x': 0.48173195, 'y': 0.36561066}, {'x': 0.48786986, 'y': 0.36666667}, {'x': 0.4935326, 'y': 0.36803946}, {'x': 0.50142086, 'y': 0.36537328}, {'x': 0.5087515, 'y': 0.3639211}, {'x': 0.5122759, 'y': 0.35339713}]}}]}}. Error was: Detected that custom integration 'camect' calls async_fire from a thread at custom_components/camect/camecthub.py, line 223: self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data). Please report it to the author of the 'camect' custom integration.
Traceback (most recent call last):
  File "/config/custom_components/camect/camecthub.py", line 179, in handle_camect_event
    self.fire_camera_event(ATTR_ALERT, evt)
  File "/config/custom_components/camect/camecthub.py", line 223, in fire_camera_event
    self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'camect' calls async_fire from a thread at custom_components/camect/camecthub.py, line 223: self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data). Please report it to the author of the 'camect' custom integration.
```
I don't believe I was receiving this error in 2024.04.x

**Comment by epleypa** [comment]
Experiencing this issue too, home assistant logs provides the following additional information to fix: 
`RuntimeError: Detected that custom integration 'camect' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/camect/camecthub.py, line 223: self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data). Please report it to the author of the 'camect' custom integration.`
