### ISSUE TITLE
Support for multiple Camect Hubs

### ISSUE THREAD

**Issue by kanebullen** [Fr3d/camect-ha#9]
Hi,

I previously used the old Camect integration - and had this successfully working with two hubs.        Saw a suggestion to move to your new integration, and have done so, but don't seem to be able to get two hubs to work - can only connect to my first one.

Can I offer assistance to help get this working?

I have tried adding a second integration, leaving hostname as local.home.camect.com, and it comes up with "Unexpected Error".       Also tried adding using the IP address of the second unit, and same result.

Thanks
Kane

2024-12-10 17:30:23.269 ERROR (MainThread) [custom_components.camect.config_flow] Unexpected exception: Flow aborted: already_configured
Traceback (most recent call last):
  File "/config/custom_components/camect/config_flow.py", line 128, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1607, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by kanebullen** [comment]
Update:     

Was able to get the second hub added.  Not via the local 192.168.* address, but by grabbing the URL for the second hub from the following URL that I found in your code:

https://local.home.camect.com/list.json

My offer is still there to help out if you'd like to add support for the choice of which hub to add (rather than the hardcoded json[0] currently in there)
